# Generated by Django 5.2.7 on 2025-10-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.CharField(max_length=255)),
                ('image', models.URLField(help_text='URL da imagem do imóvel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
