# Generated by Django 5.2.7 on 2025-10-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='anuncios/')),
                ('legenda', models.CharField(blank=True, max_length=255)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='listings.listing')),
            ],
        ),
    ]
